name: avisualidentity-contact-api
services:
- name: contact-api
  source_dir: /
  github:
    repo: davodey/avisualidentity
    branch: master
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GMAIL_USER
    value: davodey@gmail.com
  - key: GMAIL_APP_PASSWORD
    value: ${GMAIL_APP_PASSWORD}
    type: SECRET
